const mongoose=require('mongoose');
const ObjectId=mongoose.Schema.Types.ObjectId;

const forecastSchema= new mongoose.Schema({
sunday:{
    date:{
        type:String,required:true
    },
    temperature:{
        type:Number,
        required:true
    }
},
monday:{
    date:{
        type:String,required:true
    },
    temperature:{
        type:Number,
        required:true
    }
},
tuesday:{
    date:{
        type:String,required:true
    },
    temperature:{
        type:Number,
        required:true
    }
},
wednesday:{
    date:{
        type:String,required:true
    },
    temperature:{
        type:Number,
        required:true
    }
},
thursday:{
    date:{
        type:String,required:true
    },
    temperature:{
        type:Number,
        required:true
    } 
},
friday:{
    date:{
        type:String,required:true
    }, 
    temperature:{ 
        type:Number, 
        required:true
    }
},
saturday:{
    date:{
        type:String,required:true
    },
    temperature:{
        type:Number, 
        required:true
    }
},
cityId:{
    type:ObjectId,ref:"city",
    required:true
}},{timestamps:true}
)

module.exports=mongoose.model("forecast",forecastSchema);